// <auto-generated />
using System;
using Drammers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drammers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DrammersDbContext))]
    [Migration("20260925113059_IdentityAndRbac")]
    partial class IdentityAndRbac
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.AppConfigurationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("PK_AppConfiguration");

                    b.ToTable("AppConfiguration", "config");

                    b.HasData(
                        new
                        {
                            Key = "min_app_version_ios",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "min_app_version_android",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "recommended_app_version",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "maintenance_mode",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "maintenance_message",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        },
                        new
                        {
                            Key = "support_email",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        });
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.FeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Key")
                        .HasName("PK_FeatureFlag");

                    b.ToTable("FeatureFlag", "config");
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.RetentionPolicy", b =>
                {
                    b.Property<string>("DataType")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("data_type");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int")
                        .HasColumnName("retention_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("DataType")
                        .HasName("PK_RetentionPolicy");

                    b.ToTable("RetentionPolicy", "config", t =>
                        {
                            t.HasCheckConstraint("CK_RetentionPolicy_action", "[action] IN ('Delete', 'Anonymize', 'Aggregate')");
                        });

                    b.HasData(
                        new
                        {
                            DataType = "member_former",
                            Action = "Anonymize",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "membership_application_rejected",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "guardian_account_without_child",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "account_request_rejected",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 92
                        },
                        new
                        {
                            DataType = "login_history",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "ticket_scan",
                            Action = "Aggregate",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "ticket_order_payment",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 2557
                        },
                        new
                        {
                            DataType = "parade_registration",
                            Action = "Anonymize",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 1096
                        },
                        new
                        {
                            DataType = "parade_document",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "notification",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "push_token_inactive",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "audit_log",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "audit_log_financial_privacy",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 2557
                        });
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.ScheduledJobState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_completed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LastInstance")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_instance");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_started_at");

                    b.Property<DateTime?>("LastSucceededAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_succeeded_at");

                    b.HasKey("Name")
                        .HasName("PK_ScheduledJob");

                    b.ToTable("ScheduledJob", "config");
                });

            modelBuilder.Entity("Drammers.Modules.Audit.AuditLog.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("device_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("HashPrev")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash_prev")
                        .IsFixedLength();

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.HasKey("Id")
                        .HasName("PK_AuditLog");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLog_actor_user_id_occurred_at");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLog_entity_type_entity_id_occurred_at");

                    b.ToTable("AuditLog", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_actor_type", "[actor_type] IN ('User', 'System', 'Sync', 'Webhook')");
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Content.CarnivalYears.CarnivalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateOnly>("CarnivalEndDate")
                        .HasColumnType("date")
                        .HasColumnName("carnival_end_date");

                    b.Property<DateOnly>("CarnivalStartDate")
                        .HasColumnType("date")
                        .HasColumnName("carnival_start_date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("PK_CarnivalYear");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasDatabaseName("IX_CarnivalYear_active")
                        .HasFilter("[active] = 1");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CarnivalYear_name");

                    b.ToTable("CarnivalYear", "content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CarnivalEndDate = new DateOnly(2027, 2, 9),
                            CarnivalStartDate = new DateOnly(2027, 2, 6),
                            EndDate = new DateOnly(2027, 2, 10),
                            Name = "2026/2027",
                            StartDate = new DateOnly(2026, 11, 11)
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Provisioning.AccountProvisioning", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("EbMemberId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("eb_member_id");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("entra_object_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<string>("MemberNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("member_number");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("step");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_AccountProvisioning");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_AccountProvisioning_source_type_source_id");

                    b.ToTable("AccountProvisioning", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_AccountProvisioning_kind", "[kind] IN ('Member', 'Guardian', 'Administrator')");

                            t.HasCheckConstraint("CK_AccountProvisioning_source_type", "[source_type] IN ('MembershipApplication', 'AccountRequest', 'Guardian', 'Manual')");

                            t.HasCheckConstraint("CK_AccountProvisioning_step", "[step] IN ('Pending', 'EbCreated', 'MemberCreated', 'AccountCreated', 'WelcomeSent', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Roles.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PK_Permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_code");

                    b.ToTable("Permission", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Leden",
                            Code = "member.read.own",
                            Description = "Eigen gegevens en lidmaatschap bekijken"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Leden",
                            Code = "member.read",
                            Description = "Leden bekijken en zoeken"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Leden",
                            Code = "member.update",
                            Description = "Lokale ledengegevens wijzigen"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Leden",
                            Code = "member.approve",
                            Description = "Lidmaatschapsaanvragen beoordelen"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Leden",
                            Code = "member.export",
                            Description = "Ledenlijsten exporteren"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Leden",
                            Code = "member.block",
                            Description = "Accounts en toegang blokkeren"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Leden",
                            Code = "member.privacy",
                            Description = "AVG-verzoeken afhandelen"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Leden",
                            Code = "guardian.read.own",
                            Description = "Gegevens en meldingen van eigen kinderen"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Content",
                            Code = "event.read",
                            Description = "Leden-events bekijken"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Content",
                            Code = "event.manage",
                            Description = "Agenda en programma beheren"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Content",
                            Code = "news.read",
                            Description = "Ledennieuws bekijken"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Content",
                            Code = "news.manage",
                            Description = "Nieuws beheren en publiceren"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Content",
                            Code = "photo.read",
                            Description = "Ledenfoto's bekijken"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Content",
                            Code = "photo.manage",
                            Description = "Albums en foto's beheren"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Meldingen",
                            Code = "notification.read.own",
                            Description = "Eigen inbox"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Meldingen",
                            Code = "notification.send",
                            Description = "Meldingen versturen naar elke doelgroep"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Meldingen",
                            Code = "notification.send.group",
                            Description = "Meldingen versturen naar eigen groep(en)"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Meldingen",
                            Code = "notification.send.urgent",
                            Description = "Categorie Dringend gebruiken"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Optocht",
                            Code = "parade.read",
                            Description = "Optochtinschrijvingen inzien"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Optocht",
                            Code = "parade.register",
                            Description = "Optochtinschrijving starten"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Optocht",
                            Code = "parade.update",
                            Description = "Eigen inschrijving wijzigen binnen het statusbeleid"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Optocht",
                            Code = "parade.manage",
                            Description = "Inschrijvingen beoordelen en wijzigen"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Optocht",
                            Code = "parade.manage-final",
                            Description = "Wijzigen na status Final"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Optocht",
                            Code = "parade.assign-start-number",
                            Description = "Startnummers en volgorde toekennen"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Optocht",
                            Code = "parade.import-arrival-times",
                            Description = "Aanrijtijden importeren en publiceren"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Optocht",
                            Code = "parade.export",
                            Description = "Optochtexports"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Optocht",
                            Code = "parade.config",
                            Description = "Optochten en categorieën configureren"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Toegang",
                            Code = "ticket.read.own",
                            Description = "Eigen tickets en QR"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Toegang",
                            Code = "ticket.read",
                            Description = "Tickets en scanlogs inzien"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Toegang",
                            Code = "ticket.scan",
                            Description = "Scanmodus gebruiken (alleen op trusted device)"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Toegang",
                            Code = "ticket.scan.details",
                            Description = "Extra details bij een scan"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Toegang",
                            Code = "ticket.manage",
                            Description = "Tickets en scanners beheren"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Financieel",
                            Code = "payment.read",
                            Description = "Betalingen en orders inzien"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Financieel",
                            Code = "payment.manage",
                            Description = "Refunds en handmatige correcties"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Beheer",
                            Code = "report.view",
                            Description = "Rapportages en dashboards"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Beheer",
                            Code = "import.run",
                            Description = "Sync en imports starten, conflicten afhandelen"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Beheer",
                            Code = "audit.read",
                            Description = "Auditlog inzien"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Beheer",
                            Code = "role.manage",
                            Description = "Rollen, permissions en toewijzingen beheren"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Beheer",
                            Code = "config.manage",
                            Description = "Carnavalsjaar, feature flags, appversie, bewaartermijnen"
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAssignableBySync")
                        .HasColumnType("bit")
                        .HasColumnName("is_assignable_by_sync");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK_Role");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_code");

                    b.ToTable("Role", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "lid",
                            Description = "Lid van de vereniging (systeemrol)",
                            IsAssignableBySync = true,
                            IsSystem = true,
                            Name = "Carnavalist",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 2,
                            Code = "groepsverantwoordelijke",
                            Description = "Beheert eigen optochtinschrijvingen",
                            IsAssignableBySync = true,
                            IsSystem = false,
                            Name = "Groepsverantwoordelijke",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 3,
                            Code = "kaderlid",
                            Description = "Kader; vooral via doelgroepen",
                            IsAssignableBySync = true,
                            IsSystem = false,
                            Name = "Kaderlid",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 4,
                            Code = "dansgarde-leiding",
                            Description = "Leiding van de dansgarde",
                            IsAssignableBySync = true,
                            IsSystem = false,
                            Name = "Dansgarde leiding",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 5,
                            Code = "dansgarde-lid",
                            Description = "Lid van de dansgarde",
                            IsAssignableBySync = true,
                            IsSystem = false,
                            Name = "Dansgarde lid",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = 6,
                            Code = "ouder",
                            Description = "Ouder of verzorger van een minderjarig lid (systeemrol)",
                            IsAssignableBySync = true,
                            IsSystem = true,
                            Name = "Ouder/verzorger",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = 7,
                            Code = "raad-van-elf",
                            Description = "Raad van Elf",
                            IsAssignableBySync = true,
                            IsSystem = false,
                            Name = "Raad van Elf",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = 8,
                            Code = "scanner",
                            Description = "Mag scannen op een trusted device (eventueel tijdelijk)",
                            IsAssignableBySync = false,
                            IsSystem = false,
                            Name = "Scanner",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = 9,
                            Code = "optochtcommissie",
                            Description = "Organisatie van de optocht",
                            IsAssignableBySync = false,
                            IsSystem = false,
                            Name = "Optochtcommissie",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = 10,
                            Code = "redactie",
                            Description = "Nieuws, agenda en foto's",
                            IsAssignableBySync = false,
                            IsSystem = false,
                            Name = "Redactie",
                            SortOrder = 100
                        },
                        new
                        {
                            Id = 11,
                            Code = "bestuur",
                            Description = "Bestuur van de vereniging (systeemrol)",
                            IsAssignableBySync = false,
                            IsSystem = true,
                            Name = "Bestuur",
                            SortOrder = 110
                        },
                        new
                        {
                            Id = 12,
                            Code = "beheerder-it",
                            Description = "Technisch beheer, zonder inhoudelijke rechten op betalingen en goedkeuringen (systeemrol)",
                            IsAssignableBySync = false,
                            IsSystem = true,
                            Name = "Beheerder (IT)",
                            SortOrder = 120
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("PK_RolePermission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermission_permission_id");

                    b.ToTable("RolePermission", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 39
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Users.LoginHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_hash");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("result");

                    b.Property<string>("SubjectHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("subject_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_LoginHistory");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_LoginHistory_occurred_at");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_LoginHistory_user_id_occurred_at");

                    b.ToTable("LoginHistory", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_LoginHistory_result", "[result] IN ('Success', 'Failed', 'Locked')");
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("account_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_object_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_login_at");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("member_id");

                    b.Property<int>("PermissionsVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("permissions_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_User_email");

                    b.HasIndex("ExternalObjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_User_external_object_id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_User_member_id")
                        .HasFilter("[member_id] IS NOT NULL");

                    b.ToTable("User", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_User_account_status", "[account_status] IN ('Active', 'Disabled', 'Blocked', 'Deleted')");
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRole");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRole_role_id");

                    b.ToTable("UserRole", "identity");
                });

            modelBuilder.Entity("Drammers.Modules.Notification.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("locked_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK_Outbox");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Outbox_created_at")
                        .HasFilter("[processed_at] IS NULL");

                    b.ToTable("Outbox", "notification");
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Roles.RolePermission", b =>
                {
                    b.HasOne("Drammers.Modules.Identity.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drammers.Modules.Identity.Roles.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Users.UserRole", b =>
                {
                    b.HasOne("Drammers.Modules.Identity.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Drammers.Modules.Identity.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Drammers.Modules.Identity.Users.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
