// <auto-generated />
using System;
using Drammers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drammers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DrammersDbContext))]
    [Migration("20260925094818_DatabaseRoles")]
    partial class DatabaseRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.AppConfigurationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("PK_AppConfiguration");

                    b.ToTable("AppConfiguration", "config");

                    b.HasData(
                        new
                        {
                            Key = "min_app_version_ios",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "min_app_version_android",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "recommended_app_version",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "1.0.0"
                        },
                        new
                        {
                            Key = "maintenance_mode",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "false"
                        },
                        new
                        {
                            Key = "maintenance_message",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        },
                        new
                        {
                            Key = "support_email",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = ""
                        });
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.FeatureFlag", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Key")
                        .HasName("PK_FeatureFlag");

                    b.ToTable("FeatureFlag", "config");
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.RetentionPolicy", b =>
                {
                    b.Property<string>("DataType")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("data_type");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int")
                        .HasColumnName("retention_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("DataType")
                        .HasName("PK_RetentionPolicy");

                    b.ToTable("RetentionPolicy", "config", t =>
                        {
                            t.HasCheckConstraint("CK_RetentionPolicy_action", "[action] IN ('Delete', 'Anonymize', 'Aggregate')");
                        });

                    b.HasData(
                        new
                        {
                            DataType = "member_former",
                            Action = "Anonymize",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "membership_application_rejected",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "guardian_account_without_child",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "account_request_rejected",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 92
                        },
                        new
                        {
                            DataType = "login_history",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "ticket_scan",
                            Action = "Aggregate",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "ticket_order_payment",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 2557
                        },
                        new
                        {
                            DataType = "parade_registration",
                            Action = "Anonymize",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 1096
                        },
                        new
                        {
                            DataType = "parade_document",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "notification",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 365
                        },
                        new
                        {
                            DataType = "push_token_inactive",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 183
                        },
                        new
                        {
                            DataType = "audit_log",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 730
                        },
                        new
                        {
                            DataType = "audit_log_financial_privacy",
                            Action = "Delete",
                            CreatedAt = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RetentionDays = 2557
                        });
                });

            modelBuilder.Entity("Drammers.Infrastructure.Configuration.ScheduledJobState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_completed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LastInstance")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_instance");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_started_at");

                    b.Property<DateTime?>("LastSucceededAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("last_succeeded_at");

                    b.HasKey("Name")
                        .HasName("PK_ScheduledJob");

                    b.ToTable("ScheduledJob", "config");
                });

            modelBuilder.Entity("Drammers.Modules.Audit.AuditLog.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("device_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("HashPrev")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash_prev")
                        .IsFixedLength();

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.HasKey("Id")
                        .HasName("PK_AuditLog");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLog_actor_user_id_occurred_at");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLog_entity_type_entity_id_occurred_at");

                    b.ToTable("AuditLog", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_actor_type", "[actor_type] IN ('User', 'System', 'Sync', 'Webhook')");
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Content.CarnivalYears.CarnivalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<DateOnly>("CarnivalEndDate")
                        .HasColumnType("date")
                        .HasColumnName("carnival_end_date");

                    b.Property<DateOnly>("CarnivalStartDate")
                        .HasColumnType("date")
                        .HasColumnName("carnival_start_date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("PK_CarnivalYear");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasDatabaseName("IX_CarnivalYear_active")
                        .HasFilter("[active] = 1");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CarnivalYear_name");

                    b.ToTable("CarnivalYear", "content");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CarnivalEndDate = new DateOnly(2027, 2, 9),
                            CarnivalStartDate = new DateOnly(2027, 2, 6),
                            EndDate = new DateOnly(2027, 2, 10),
                            Name = "2026/2027",
                            StartDate = new DateOnly(2026, 11, 11)
                        });
                });

            modelBuilder.Entity("Drammers.Modules.Notification.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("locked_until");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PK_Outbox");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Outbox_created_at")
                        .HasFilter("[processed_at] IS NULL");

                    b.ToTable("Outbox", "notification");
                });
#pragma warning restore 612, 618
        }
    }
}
